@startsalt Plan: CRM Tab
{ 
    {+ https://capa5.ag7if.net/plans/utwg-1-1-2026 }
    {+
        {* [<&home>] | <b>Plans</b> | Activities | About | [<&moon>] | [<&person>] }
        .
        { ^DRAFT^ {<b>OPLAN UTWG 1-1-2026: Desert Hawk XXIII</b>}}
        .u
        {/ eSSS | Plan | <b>CRM</b> | Team }
        {+
            .
            <b><u>Tasks</u></b>
            .
            {#
                Tasks                   | Tab           | ASSIGNED BY | ASSIGNED TO   | SUSPENSE     | COMPLETED 
                Finalize Command Intent | Sec. 3.1.1    | DHXXIII/CC  | DHXXIII/CC    | 5 Aug 2025   | "        "
                Create more busywork    | Sec. 3.1.1    | DHXXIII/CC  | DHXXIII/CDC   | 1 Aug 2025   | .
                Fetch Coffee            | UTWG 1-1-2026 | DHXXIII/CC  | DHXXIII/CDS   | 1 Jul 2025   | 3 Jul 2025
            }
            {[New Task] | [Show Completed] | [Show Assigned to Me]}

            .
            <b><u>Comments</u></b>
            .
            {#
                From        | To         | Comment Type | Tab        | Location | Comment                                         | Decision | Rationale
                DHXXIII/SE  | DHXXIII/CC | Critical     | Sec. 3.1.1 | N/A      | Insufficient busywork                           | ^Accept^ | "       "
                DHXXIII/CDC | DHXXIII/CC | Substantive  | Sec. 3.1.1 | N/A      | Instructions unclear, sewed name tapes to blues | ^      ^ | "       "
            }
            {[New Comment] | [Show Resolved] | [Show Assigned to Me]}
        }
    }
}
@endsalt
